export const mockRowsLeaderboard = [
  {
    rank: 1,
    username: 'Dr. Peter Attia',
    category: 'Medicine',
    score: 94,
    trend: 'up',
    followers: '1.2M+',
    tweets: 203,
    imageInfluencer: './will.png',
  },
  {
    rank: 2,
    username: 'Dr. Rhonda Patrick',
    category: 'Nutrition',
    score: 91,
    trend: 'up',
    followers: '980K+',
    tweets: 156,
    imageInfluencer: './woman.png',
  },
  {
    rank: 3,
    username: 'Dr. Chris Palmer',
    category: 'Mental Health',
    score: 90,
    trend: 'up',
    followers: '180K+',
    tweets: 76,
    imageInfluencer: './kanye.png',
  },
  {
    rank: 4,
    username: 'Andrew Huberman',
    category: 'Neuroscience',
    score: 89,
    trend: 'up',
    followers: '4.2M+',
    tweets: 127,
    imageInfluencer: './kanye.png',
  },
  {
    rank: 5,
    username: 'Dr. Dominic D’Agostino',
    category: 'Nutrition',
    score: 89,
    trend: 'down',
    followers: '290K+',
    tweets: 112,
    imageInfluencer: './will.png',
  },
  {
    rank: 6,
    username: 'Dr. Gabrielle Lyon',
    category: 'Medicine',
    score: 88,
    trend: 'up',
    followers: '380K+',
    tweets: 84,
    imageInfluencer: './woman.png',
  },
  {
    rank: 7,
    username: 'Dr. David Sinclair',
    category: 'Longevity',
    score: 87,
    trend: 'up',
    followers: '1.1M+',
    tweets: 145,
    imageInfluencer: './kanye.png',
  },
  {
    rank: 8,
    username: 'Dr. Mark Hyman',
    category: 'Nutrition',
    score: 86,
    trend: 'up',
    followers: '1.5M+',
    tweets: 160,
    imageInfluencer: './kanye.png',
  },
  {
    rank: 9,
    username: 'Dr. Steven Gundry',
    category: 'Cardiology',
    score: 85,
    trend: 'down',
    followers: '1.8M+',
    tweets: 120,
    imageInfluencer: './will.png',
  },
  {
    rank: 10,
    username: 'Dr. Terry Wahls',
    category: 'Functional Medicine',
    score: 84,
    trend: 'up',
    followers: '320K+',
    tweets: 88,
    imageInfluencer: './woman.png',
  },
  {
    rank: 12,
    username: 'Dr. Michael Greger',
    category: 'Nutrition',
    score: 83,
    trend: 'up',
    followers: '2M+',
    tweets: 200,
    imageInfluencer: './kanye.png',
  },
  {
    rank: 13,
    username: 'Dr. Jason Fung',
    category: 'Endocrinology',
    score: 82,
    trend: 'down',
    followers: '400K+',
    tweets: 95,
    imageInfluencer: './kanye.png',
  },
  {
    rank: 14,
    username: 'Dr. Ben Greenfield',
    category: 'Fitness',
    score: 81,
    trend: 'up',
    followers: '750K+',
    tweets: 130,
    imageInfluencer: './will.png',
  },
  {
    rank: 15,
    username: 'Dr. Tim Spector',
    category: 'Gut Health',
    score: 80,
    trend: 'up',
    followers: '300K+',
    tweets: 70,
    imageInfluencer: './kanye.png',
  },
  {
    rank: 16,
    username: 'Dr. Sara Gottfried',
    category: 'Hormone Health',
    score: 79,
    trend: 'down',
    followers: '650K+',
    tweets: 90,
    imageInfluencer: './woman.png',
  },
  {
    rank: 17,
    username: 'Dr. Dale Bredesen',
    category: 'Neurology',
    score: 78,
    trend: 'up',
    followers: '200K+',
    tweets: 65,
    imageInfluencer: './will.png',
  },
  {
    rank: 18,
    username: 'Dr. Joe Dispenza',
    category: 'Mindset',
    score: 77,
    trend: 'up',
    followers: '2.5M+',
    tweets: 180,
    imageInfluencer: './kanye.png',
  },
  {
    rank: 19,
    username: 'Dr. Kelly Brogan',
    category: 'Psychiatry',
    score: 76,
    trend: 'down',
    followers: '100K+',
    tweets: 50,
    imageInfluencer: './woman.png',
  },
  {
    rank: 20,
    username: 'Dr. William Li',
    category: 'Cancer Research',
    score: 75,
    trend: 'up',
    followers: '600K+',
    tweets: 105,
    imageInfluencer: './kanye.png',
  },
  {
    rank: 21,
    username: 'Dr. Daniel Amen',
    category: 'Brain Health',
    score: 74,
    trend: 'up',
    followers: '1.3M+',
    tweets: 140,
    imageInfluencer: './will.png',
  },
  ];