export const mock_rank_influencers = [
  {
    id: 1,
    username: 'Dr. Peter Attia',
    created_at: '01/01/2000',
    category: 'Medicine',
    trend: 'up',
    followers: '1.2M+',
    tweets_number: '203',
    score: '94',
  },
  {
    id: 2,
    username: 'Dr. Rhonda Patrick',
    created_at: '01/01/2000',
    category: 'Nutrition',
    trend: 'up',
    followers: '980K+',
    tweets_number: '156',
    score: '91',
  },
  {
    id: 3,
    username: 'Dr. Chris Palmer',
    created_at: '01/01/2000',
    category: 'Mental Health',
    trend: 'up',
    followers: '180K+',
    tweets_number: '76',
    score: '90',
  },
  {
    id: 4,
    username: 'Andrew Huberman',
    created_at: '01/01/2000',
    category: 'Neuroscience',
    trend: 'up',
    followers: '4.2M+',
    tweets_number: '127',
    score: '89',
  },
  {
    id: 5,
    username: 'Dr. Dominic D’Agostino',
    created_at: '01/01/2000',
    category: 'Nutrition',
    trend: 'down',
    followers: '290K+',
    tweets_number: '112',
    score: '89',
  },
  {
    id: 6,
    username: 'Dr. Gabrielle Lyon',
    created_at: '01/01/2000',
    category: 'Medicine',
    trend: 'up',
    followers: '380K+',
    tweets_number: '84',
    score: '88',
  },
  {
    id: 7,
    username: 'Dr. David Sinclair',
    created_at: '01/01/2000',
    category: 'Longevity',
    trend: 'up',
    followers: '1.1M+',
    tweets_number: '145',
    score: '87',
  },
  {
    id: 8,
    username: 'Dr. Mark Hyman',
    created_at: '01/01/2000',
    category: 'Nutrition',
    trend: 'up',
    followers: '1.5M+',
    tweets_number: '160',
    score: '86',
  },
  {
    id: 9,
    username: 'Dr. Steven Gundry',
    created_at: '01/01/2000',
    category: 'Cardiology',
    trend: 'down',
    followers: '1.8M+',
    tweets_number: '120',
    score: '85',
  },
  {
    id: 10,
    username: 'Dr. Terry Wahls',
    created_at: '01/01/2000',
    category: 'Functional Medicine',
    trend: 'up',
    followers: '320K+',
    tweets_number: '88',
    score: '84',
  },
  {
    id: 12,
    username: 'Dr. Michael Greger',
    created_at: '01/01/2000',
    category: 'Nutrition',
    trend: 'up',
    followers: '2M+',
    tweets_number: '200',
    score: '83',
  },
  {
    id: 13,
    username: 'Dr. Jason Fung',
    created_at: '01/01/2000',
    category: 'Endocrinology',
    trend: 'down',
    followers: '400K+',
    tweets_number: '95',
    score: '82',
  },
  {
    id: 14,
    username: 'Dr. Ben Greenfield',
    created_at: '01/01/2000',
    category: 'Fitness',
    trend: 'up',
    followers: '750K+',
    tweets_number: '130',
    score: '81',
  },
  {
    id: 15,
    username: 'Dr. Tim Spector',
    created_at: '01/01/2000',
    category: 'Gut Health',
    trend: 'up',
    followers: '300K+',
    tweets_number: '70',
    score: '80',
  },
  {
    id: 16,
    username: 'Dr. Sara Gottfried',
    created_at: '01/01/2000',
    category: 'Hormone Health',
    trend: 'down',
    followers: '650K+',
    tweets_number: '90',
    score: '79',
  },
  {
    id: 17,
    username: 'Dr. Dale Bredesen',
    created_at: '01/01/2000',
    category: 'Neurology',
    trend: 'up',
    followers: '200K+',
    tweets_number: '65',
    score: '78',
  },
  {
    id: 18,
    username: 'Dr. Joe Dispenza',
    created_at: '01/01/2000',
    category: 'Mindset',
    trend: 'up',
    followers: '2.5M+',
    tweets_number: '180',
    score: '77',
  },
  {
    id: 19,
    username: 'Dr. Kelly Brogan',
    created_at: '01/01/2000',
    category: 'Psychiatry',
    trend: 'down',
    followers: '100K+',
    tweets_number: '50',
    score: '76',
  },
  {
    id: 20,
    username: 'Dr. William Li',
    created_at: '01/01/2000',
    category: 'Cancer Research',
    trend: 'up',
    followers: '600K+',
    tweets_number: '105',
    score: '75',
  },
  {
    id: 21,
    username: 'Dr. Daniel Amen',
    created_at: '01/01/2000',
    category: 'Brain Health',
    trend: 'up',
    followers: '1.3M+',
    tweets_number: '140',
    score: '74',
  },
  ];