export const mockRowsLeaderboard = [
  {
    rank: 1,
    name: 'Dr. Peter Attia',
    category: 'Medicine',
    trustScore: 94,
    trend: 'up',
    followers: '1.2M+',
    verifiedClaims: 203,
    imageInfluencer: './will.png',
  },
  {
    rank: 2,
    name: 'Dr. Rhonda Patrick',
    category: 'Nutrition',
    trustScore: 91,
    trend: 'up',
    followers: '980K+',
    verifiedClaims: 156,
    imageInfluencer: './woman.png',
  },
  {
    rank: 3,
    name: 'Dr. Chris Palmer',
    category: 'Mental Health',
    trustScore: 90,
    trend: 'up',
    followers: '180K+',
    verifiedClaims: 76,
    imageInfluencer: './kanye.png',
  },
  {
    rank: 4,
    name: 'Andrew Huberman',
    category: 'Neuroscience',
    trustScore: 89,
    trend: 'up',
    followers: '4.2M+',
    verifiedClaims: 127,
    imageInfluencer: './kanye.png',
  },
  {
    rank: 5,
    name: 'Dr. Dominic D’Agostino',
    category: 'Nutrition',
    trustScore: 89,
    trend: 'down',
    followers: '290K+',
    verifiedClaims: 112,
    imageInfluencer: './will.png',
  },
  {
    rank: 6,
    name: 'Dr. Gabrielle Lyon',
    category: 'Medicine',
    trustScore: 88,
    trend: 'up',
    followers: '380K+',
    verifiedClaims: 84,
    imageInfluencer: './woman.png',
  },
  {
    rank: 7,
    name: 'Dr. David Sinclair',
    category: 'Longevity',
    trustScore: 87,
    trend: 'up',
    followers: '1.1M+',
    verifiedClaims: 145,
    imageInfluencer: './kanye.png',
  },
  {
    rank: 8,
    name: 'Dr. Mark Hyman',
    category: 'Nutrition',
    trustScore: 86,
    trend: 'up',
    followers: '1.5M+',
    verifiedClaims: 160,
    imageInfluencer: './kanye.png',
  },
  {
    rank: 9,
    name: 'Dr. Steven Gundry',
    category: 'Cardiology',
    trustScore: 85,
    trend: 'down',
    followers: '1.8M+',
    verifiedClaims: 120,
    imageInfluencer: './will.png',
  },
  {
    rank: 10,
    name: 'Dr. Terry Wahls',
    category: 'Functional Medicine',
    trustScore: 84,
    trend: 'up',
    followers: '320K+',
    verifiedClaims: 88,
    imageInfluencer: './woman.png',
  },
  {
    rank: 12,
    name: 'Dr. Michael Greger',
    category: 'Nutrition',
    trustScore: 83,
    trend: 'up',
    followers: '2M+',
    verifiedClaims: 200,
    imageInfluencer: './kanye.png',
  },
  {
    rank: 13,
    name: 'Dr. Jason Fung',
    category: 'Endocrinology',
    trustScore: 82,
    trend: 'down',
    followers: '400K+',
    verifiedClaims: 95,
    imageInfluencer: './kanye.png',
  },
  {
    rank: 14,
    name: 'Dr. Ben Greenfield',
    category: 'Fitness',
    trustScore: 81,
    trend: 'up',
    followers: '750K+',
    verifiedClaims: 130,
    imageInfluencer: './will.png',
  },
  {
    rank: 15,
    name: 'Dr. Tim Spector',
    category: 'Gut Health',
    trustScore: 80,
    trend: 'up',
    followers: '300K+',
    verifiedClaims: 70,
    imageInfluencer: './kanye.png',
  },
  {
    rank: 16,
    name: 'Dr. Sara Gottfried',
    category: 'Hormone Health',
    trustScore: 79,
    trend: 'down',
    followers: '650K+',
    verifiedClaims: 90,
    imageInfluencer: './woman.png',
  },
  {
    rank: 17,
    name: 'Dr. Dale Bredesen',
    category: 'Neurology',
    trustScore: 78,
    trend: 'up',
    followers: '200K+',
    verifiedClaims: 65,
    imageInfluencer: './will.png',
  },
  {
    rank: 18,
    name: 'Dr. Joe Dispenza',
    category: 'Mindset',
    trustScore: 77,
    trend: 'up',
    followers: '2.5M+',
    verifiedClaims: 180,
    imageInfluencer: './kanye.png',
  },
  {
    rank: 19,
    name: 'Dr. Kelly Brogan',
    category: 'Psychiatry',
    trustScore: 76,
    trend: 'down',
    followers: '100K+',
    verifiedClaims: 50,
    imageInfluencer: './woman.png',
  },
  {
    rank: 20,
    name: 'Dr. William Li',
    category: 'Cancer Research',
    trustScore: 75,
    trend: 'up',
    followers: '600K+',
    verifiedClaims: 105,
    imageInfluencer: './kanye.png',
  },
  {
    rank: 21,
    name: 'Dr. Daniel Amen',
    category: 'Brain Health',
    trustScore: 74,
    trend: 'up',
    followers: '1.3M+',
    verifiedClaims: 140,
    imageInfluencer: './will.png',
  },
  ];